@echo off
chcp 65001 >nul
REM Debug run with diagnostics enabled
set ALCHEMIST_AUTOSTART=1
set ALCHEMIST_MAP_DEBUG=1
set ALCHEMIST_RENDER_TRACE=1
set ALCHEMIST_TILE_DEBUG_SOLID=1
set ALCHEMIST_TILE_GRID=1
set ALCHEMIST_CAMERA_ORIGIN=1
set ALCHEMIST_CAMERA_TO_CONTENT=1
set ALCHEMIST_DISABLE_FOREGROUND=1
set ALCHEMIST_SAMPLE_PIXEL=1
set ALCHEMIST_SLICE_PREFERRED=1
call "%~dp0..\run_game.bat"
